KEYCLOAK_ADMIN_PWD_SECRET_ID = "keycloak/admin/password"
DEFAULT_CONFIG="config/default.yaml"
SCRIPTS_DIR="scripts"
TEMPLATES_DIR="cf_templates"
LAMBDA_DIR="lambda"
CLOUDFORMATION_CAPABILITIES = {
    "CAPABILITY_IAM",
    "CAPABILITY_NAMED_IAM",
    "CAPABILITY_AUTO_EXPAND",
    "CAPABILITY_RESOURCE_POLICY"
}