AWSTemplateFormatVersion: '2010-09-09'
Description: |
            This is the Main Template for deploying a self-managed Kubernetes cluster on AWS using CloudFormation.
            The template is organized in NestedStacks to make clearer the different components of the cluster.
            The stacks are the following ones: 
            - VPC
            - BastionHost
            - PolicyRole
            - ControlPlane
            - Worker

Parameters:
  ProjectName:
    Type: String
    Description: Name of the project
    Default: k8s-self-managed
    MinLength: 1
    MaxLength: 20

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: dev
    MinLength: 1
    MaxLength: 20
  
  S3BucketName:
    Description: Please enter the name for the S3BucketName
    Type: String
    MinLength: 5
    MaxLength: 75

  K8sClusterName:
    Description: Please enter the name for the K8sClusterName
    Type: String
    Default: my-k8s
    MinLength: 1
    MaxLength: 20

  K8sNodesHostnameMode:
    Description: Please enter the name for the K8sNodesHostnameMode
    Type: String
    Default: instance-id
    AllowedValues:
      - instance-id
      - private-dns
  
  KubernetesVersion:
    Description: Please enter the Kubernetes version
    Type: Number
    Default: 1.27
    MinValue: 1.25
    MaxValue: 1.28
  
  PodsOverlayNetworkCidr:
    Description: Please enter the Pods Overlay Network CIDR
    Type: String
    Default: 192.168.0.0/16
    AllowedPattern: ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.0\/(3[0-2]|[1-2]?[0-9])$
  
  ClusterServicesNetworkCidr:
    Description: Please enter the Cluster Services Network CIDR
    Type: String
    Default: 10.196.0.0/12
    AllowedPattern: ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.0\.0\/(3[0-2]|[1-2]?[0-9])$
  
  ClusterDefaultDns:
    Description: Please enter the Cluster Default DNS
    Type: String
    Default: cluster.local

  StackName:
    Description: Name of the stack
    Type: String
    Default: k8s-self-managed
    MinLength: 1
    MaxLength: 20
  
  VpcStackName:
    Description: Please enter the name for the VpcStackName
    Type: String
    Default: VPC
    MinLength: 1
    MaxLength: 20
  
  BastionHostStackName:
    Description: Please enter the name for the BastionHostStackName
    Type: String
    Default: BastionHost 
    MinLength: 1
    MaxLength: 20 

  AuroraStackName:
    Description: Please enter the name for the AuroraStackName
    Type: String
    Default: Aurora
    MinLength: 1
    MaxLength: 20
  
  KeycloakStackName:
    Description: Please enter the name for the KeycloakStackName
    Type: String
    Default: Keycloak
    MinLength: 1
    MaxLength: 20

  IRSAStackName:
    Description: Please enter the name for the IRSAStackName
    Type: String
    Default: IRSA
    MinLength: 1
    MaxLength: 20

  ControlPlaneStackName:
    Description: Please enter the name for the ControlPlaneStackName
    Type: String
    Default: ControlPlane
    MinLength: 1
    MaxLength: 20

  WorkerStackName:
    Description: Please enter the name for the WorkerStackName
    Type: String
    Default: Worker
    MinLength: 1
    MaxLength: 20

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 172.0.0.0/16
    AllowedPattern: ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(3[0-2]|[1-2]?[0-9])$
  
  HomeInternetRouterIp: 
    Description: Home Internet Router IP Address 
    Type: String
    Default: 79.21.217.199/32
    AllowedPattern: ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(3[0-2]|[1-2]?[0-9])$
  
  AvailabilityZones:
    Description: List of Availability Zones to use (comma-delimited)
    Type: String
    Default: "us-east-1a,us-east-1b,us-east-1c"

  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 172.0.0.0/20
    AllowedPattern: ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(3[0-2]|[1-2]?[0-9])$

  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 172.0.16.0/20
    AllowedPattern: ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(3[0-2]|[1-2]?[0-9])$

  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 172.0.32.0/20
    AllowedPattern: ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(3[0-2]|[1-2]?[0-9])$
  
  PrivateSubnet3CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the third Availability Zone
    Type: String
    Default: 172.0.48.0/20
    AllowedPattern: ^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(3[0-2]|[1-2]?[0-9])$
  
  BastionHostInstanceType:
    Description: Please enter Bastion Host Instance Type
    Type: String
    Default: t2.micro
  
  BastionHostRootVolumeSize:
    Description: Please enter Bastion Host Root Volume Size
    Type: Number
    Default: 8
    MinValue: 8
    MaxValue: 100

  AuroraMasterDBName:
    Description: Please enter the name for the DBName
    Type: String
    Default: postgres
    MinLength: 1
    MaxLength: 20

  AuroraDBPort:
    Description: Please enter the port for the DBPort
    Type: Number
    Default: 5432
    MinValue: 1
    MaxValue: 65535

  AuroraMasterDBUsername:
    Description: Please enter the username for the DBUsername
    Type: String
    Default: postgres
    MinLength: 1
    MaxLength: 30

  AuroraDBEngineVersion:
    Description: Please enter the engine version for the DBEngineVersion
    Type: String
    Default: 10.7
    MinLength: 1
    MaxLength: 20

  AuroraDBInstanceClass:
    Description: Please enter the instance class for the DBInstanceClass
    Type: String
    Default: db.t3.medium
    MinLength: 1
    MaxLength: 20

  AuroraDBSnapshotName:
    Description: Please enter the snapshot name for the DBSnapshotName
    Type: String

  AuroraDBBootStrapLambdaRepositoryName:
    Description: Please enter the repository name for the DBBootStrapLambdaRepositoryName
    Type: String
    MinLength: 1
    MaxLength: 20

  AuroraDBBootStrapLambdaImageUri:
    Description: Please enter the image uri for the DBBootStrapLambdaImageUri
    Type: String
    MinLength: 1
    MaxLength: 100
  
  KeycloakCacheS3BucketName:
    Description: Please enter the name for the KeycloakS3CacheBucketName
    Type: String
    MinLength: 1
    MaxLength: 20
  
  KeycloakInstanceType:
    Description: Please enter the instance type for the KeycloakInstanceType
    Type: String
    Default: t3.medium
  
  KeycloakInstanceRootVolumeSize:
    Description: Please enter the root volume size for the KeycloakInstanceRootVolumeSize
    Type: Number
    Default: 16
    MinValue: 16
    MaxValue: 100
  
  KeycloakAsgMaxSize:
    Description: Please enter the max size for the KeycloakAsgMaxSize
    Type: Number
    Default: 5
    MinValue: 1
    MaxValue: 10
  
  KeycloakAsgDesiredCapacity:
    Description: Please enter the desired capacity for the KeycloakAsgDesiredCapacity
    Type: Number
    Default: 2
    MinValue: 1
    MaxValue: 10
  
  KeycloakVersion:
    Description: Please enter the version for the KeycloakVersion
    Type: String
    Default: 22.0.5
    MinLength: 1
    MaxLength: 20
  
  KeycloakTopLevelDomain:
    Description:  Please enter the top level domain for the KeycloakTopLevelDomain
    Type: String
    Default: keycloak-example.com
    MinLength: 1
    MaxLength: 40
  
  KeycloakAlbSubDomainName:
    Description: Please enter the sub domain name for the KeycloakAlbSubDomainName
    Type: String
    Default: test.keycloak-example.com
    MinLength: 1
    MaxLength: 20
  
  KeycloakAuroraDBUser:
    Description: Please enter the user for the KeycloakAuroraDBUser
    Type: String
    Default: keycloak
    MinLength: 1
    MaxLength: 20
  
  KeycloakAuroraDBSchema:
    Description: Please enter the schema for the KeycloakAuroraDBSchema
    Type: String
    Default: keycloak
    MinLength: 1
    MaxLength: 20
  
  KeycloakAuroraDBDatabaseName:
    Description: Please enter the database name for the KeycloakAuroraDBDatabaseName
    Type: String
    Default: keycloak
    MinLength: 1
    MaxLength: 20

  ControlPlaneAutoScalingGroupName:
    Description: Please enter the name for the ControlPlaneAsgName
    Type: String
    Default: controlplane-asg
    MinLength: 1
    MaxLength: 20
  
  ControlPlaneAutoScalingGroupDesiredCapacity:
    Description: Please enter the desired capacity for the ControlPlaneAsgName
    Type: Number
    Default: 3
    MinValue: 1

  ControlPlaneAutoScalingGroupMaxSize:
    Description: Please enter the max size for the ControlPlaneAsgName
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 10
  
  ControlPlaneInstanceType:
    Description: Please enter the instance type for the ControlPlaneAsgName
    Type: String
    Default: t3.medium
  
  ControlPlaneRootVolumeSize:
    Description: Please enter the root volume size for the ControlPlaneAsgName
    Type: Number
    Default: 16
    MinValue: 16
    MaxValue: 100

  WorkerInstanceType:
    Description: Please enter the instance type for the WorkerAsgName
    Type: String
    Default: t3.large
  
  WorkerRootVolumeSize:
    Description: Please enter the root volume size for the WorkerAsgName
    Type: Number
    Default: 16
    MinValue: 16
    MaxValue: 100
  
  WorkerSubnet1AutoScalingGroupMaxSize:
    Description: Please enter the max size for the WorkerSubnet1AutoScalingGroup
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 100
  
  WorkerSubnet2AutoScalingGroupMaxSize:
    Description: Please enter the max size for the WorkerSubnet2AutoScalingGroup
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 100
  
  WorkerSubnet3AutoScalingGroupMaxSize:
    Description: Please enter the max size for the WorkerSubnet3AutoScalingGroup
    Type: Number
    Default: 3
    MinValue: 1
    MaxValue: 100

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BucketName}/cf_templates/vpc/stack.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        StackName: !Ref VpcStackName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
        PrivateSubnet3CIDR: !Ref PrivateSubnet3CIDR
        AvailabilityZones: !Ref AvailabilityZones
  
  BastionHostStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BucketName}/cf_templates/bastion-host/stack.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        StackName: !Ref BastionHostStackName
        S3BucketName: !Ref S3BucketName
        BastionHostInstanceType: !Ref BastionHostInstanceType
        BastionHostRootVolumeSize: !Ref BastionHostRootVolumeSize
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        VpcCIDR: !GetAtt VpcStack.Outputs.VpcCIDR
        PublicSubnet1Id: !GetAtt VpcStack.Outputs.PublicSubnet1Id
        HomeInternetRouterIp: !Ref HomeInternetRouterIp
  
  AuroraStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - VpcStack
      - BastionHostStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BucketName}/cf_templates/aurora/stack.yaml
      Parameters:
        ProjectName: !Ref ProjectName 
        EnvironmentName: !Ref EnvironmentName 
        StackName: !Ref AuroraStackName
        VpcId: !GetAtt VpcStack.Outputs.VpcId 
        VpcCIDR: !GetAtt VpcStack.Outputs.VpcCIDR 
        PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id 
        PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id 
        BastionHostSecurityGroupId: !GetAtt BastionHostStack.Outputs.BastionHostSecurityGroupId 
        MasterDBName: !Ref AuroraMasterDBName
        MasterDBUsername: !Ref AuroraMasterDBUsername
        DBPort: !Ref AuroraDBPort
        DBEngineVersion: !Ref AuroraDBEngineVersion
        DBInstanceClass: !Ref AuroraDBInstanceClass
        DBSnapshotName: !Ref AuroraDBSnapshotName
        DBBootStrapLambdaRepositoryName: !Ref DBBootStrapLambdaRepositoryName
        DBBootStrapLambdaImageUri: !Ref DBBootStrapLambdaImageUri
        LambdaBootStrapSQLStatementS3Bucket: !Ref S3BucketName 
        LambdaBootStrapSQLStatementS3Key: scripts/sql/init.sql 
  
  KeycloakStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - AuroraStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BucketName}/cf_templates/keycloak/stack.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        StackName: !Ref KeycloakStackName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        VpcCIDR: !GetAtt VpcStack.Outputs.VpcCIDR
        PublicSubnet1Id: !GetAtt VpcStack.Outputs.PublicSubnet1Id
        PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
        BastionHostSecurityGroupId: !GetAtt BastionHostStack.Outputs.BastionHostSecurityGroupId
        MainS3BucketName: !Ref S3BucketName
        CacheS3BucketName: !Ref KeycloakCacheS3BucketName
        KeycloakInstanceType: !Ref KeycloakInstanceType
        KeycloakInstanceRootVolumeSize: !Ref KeycloakInstanceRootVolumeSize
        KeycloakAsgName: keycloak-asg
        KeycloakAsgMinSize: 1
        KeycloakAsgMaxSize: !Ref KeycloakAsgMaxSize
        KeycloakAsgDesiredCapacity: !Ref KeycloakAsgDesiredCapacity
        KeycloakVersion: !Ref KeycloakVersion
        KeycloakTopLevelDomain: !Ref KeycloakTopLevelDomain
        KeycloakAlbSubDomainName: !Ref KeycloakAlbSubDomainName
        AuroraDBHost: !GetAtt AuroraStack.Outputs.ClusterEndpoint
        AuroraDBPort: !Ref AuroraDBPort
        KeycloakAuroraDBUser: !Ref KeycloakAuroraDBUser
        KeycloakAuroraDBSchema: !Ref KeycloakAuroraDBSchema
        KeycloakAuroraDBDatabaseName: !Ref KeycloakAuroraDBDatabaseName
  
  IRSAStack:
    Type: AWS::CloudFormation::Stack
    DeoendsOn:
      - KeycloakStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BucketName}/cf_templates/irsa/stack.yaml
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        StackName: !Ref IRSAStackName
        OidcProviderUrl: !Ref KeycloakAlbSubDomainName
        EbsCsiDriverSa: !Ref IRSAEbsCsiDriverSa
        EbsCsiDriverSaNamespace: !Ref IRSAEbsCsiDriverSaNamespace
        AwsCloudProviderSa: !Ref IRSAAwsCloudProviderSa
        AwsCloudProviderSaNamespace: !Ref IRSAAwsCloudProviderSaNamespace
        AwsLoadBalancerControllerSa: !Ref IRSAAwsLoadBalancerControllerSa
        AwsLoadBalancerControllerSaNamespace: !Ref IRSAAwsLoadBalancerControllerSaNamespace
        ClusterAutoScalerSa: !Ref IRSAClusterAutoScalerSa
        ClusterAutoScalerSaNamespace: !Ref IRSAClusterAutoScalerSaNamespace
  
  ControlPlaneStack:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - IRSAStack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${S3BucketName}/cloud-cf_templates/controlplane/stack.yaml
      Parameters:
        ProjectName: !Ref ProjectName
        EnvironmentName: !Ref EnvironmentName
        StackName: !Ref ControlPlaneStackName
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        VpcCIDR: !GetAtt VpcStack.Outputs.VpcCIDR
        PublicSubnet1Id: !GetAtt VpcStack.Outputs.PublicSubnet1Id
        PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
        PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
        PrivateSubnet3Id: !GetAtt VpcStack.Outputs.PrivateSubnet3Id
        BastionHostSecurityGroupId: !GetAtt BastionHostStack.Outputs.BastionHostSecurityGroupId
        K8sClusterName: !Ref K8sClusterName
        K8sNodesHostnameMode: !Ref K8sNodesHostnameMode
        PodsOverlayNetworkCidr: !Ref PodsOverlayNetworkCidr
        ClusterServicesNetworkCidr: !Ref ClusterServicesNetworkCidr
        ClusterDefaultDns: !Ref ClusterDefaultDns
        KubernetesVersion: !Ref KubernetesVersion
        ControlPlaneAutoScalingGroupName: !Ref ControlPlaneAutoScalingGroupName
        ControlPlaneAutoScalingGroupDesiredCapacity: !Ref ControlPlaneAutoScalingGroupDesiredCapacity
        ControlPlaneAutoScalingGroupMaxSize: !Ref ControlPlaneAutoScalingGroupMaxSize
        ControlPlaneInstanceType: !Ref ControlPlaneInstanceType
        ControlPlaneRootVolumeSize: !Ref ControlPlaneRootVolumeSize
        S3BucketName: !Ref S3BucketName
  
  WorkerStack:
      Type: AWS::CloudFormation::Stack
      DependsOn:
        - ControlPlaneStack
      Properties:
        TemplateURL: !Sub https://s3.amazonaws.com/${S3BucketName}/cf_templates/worker/stack.yaml
        Parameters:
          ProjectName: !Ref ProjectName
          EnvironmentName: !Ref EnvironmentName
          StackName: !Ref WorkerStackName
          VpcId: !GetAtt VpcStack.Outputs.VpcId
          VpcCIDR: !GetAtt VpcStack.Outputs.VpcCIDR
          PublicSubnet1Id: !GetAtt VpcStack.Outputs.PublicSubnet1Id
          PrivateSubnet1Id: !GetAtt VpcStack.Outputs.PrivateSubnet1Id
          PrivateSubnet2Id: !GetAtt VpcStack.Outputs.PrivateSubnet2Id
          PrivateSubnet3Id: !GetAtt VpcStack.Outputs.PrivateSubnet3Id
          BastionHostSecurityGroupId: !GetAtt BastionHostStack.Outputs.BastionHostSecurityGroupId
          K8sClusterName: !Ref K8sClusterName
          K8sNodesHostnameMode: !Ref K8sNodesHostnameMode
          KubernetesVersion: !Ref KubernetesVersion
          WorkerSubnet1AutoScalingGroupMaxSize: !Ref WorkerSubnet1AutoScalingGroupMaxSize
          WorkerSubnet2AutoScalingGroupMaxSize: !Ref WorkerSubnet2AutoScalingGroupMaxSize
          WorkerSubnet3AutoScalingGroupMaxSize: !Ref WorkerSubnet3AutoScalingGroupMaxSize
          WorkerInstanceType: !Ref WorkerInstanceType
          WorkerRootVolumeSize: !Ref WorkerRootVolumeSize
          S3BucketName: !Ref S3BucketName



